app = 'trailers-api'
primary_region = 'iad'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[mounts]
source = 'data'
destination = '/data'

[[vm]]
cpu_kind = 'shared'
memory = '512mb'
cpus = 1
