app = 'trailers-api'
primary_region = 'ord'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 4

[mounts]
source = "process"
destination = "/app/process"
